name: fire-rx
channels:
  - conda-forge
  - defaults
dependencies:
  - cairo=1.16.0
  - certifi=2023.5.7
  - cfitsio=4.2.0
  - curl=8.1.2
  - gdal=3.7.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - h5py=3.9.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.1.1
  - pandas=2.0.3
  - pytz=2023.3
  - pyyaml=6.0
  - requests=2.31.0
  - scipy=1.10.1
  - shapely=2.0.1
  - BeautifulSoup4
  - rasterio
  - pyproj
  - pyresample
  - tqdm
  - timezonefinder
  - netCDF4
  - richdem